name: Sync commits with azure devops

on:
  workflow_dispatch:
  schedule:
  - cron: "31 0 * * *" # run every day

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: 'runner'

    - uses: actions/checkout@v2
      with:
        repository: ${{secrets.TRACKER_REPO}}
        token: ${{secrets.GH_WRITE_TOKEN}}
        path: 'tracker'

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: 🔧 Update git configs
      run: git config --global user.email "iwan.li@outlook.com" && git config --global user.name "Iwan Li"

    - name: ⚙ Install node dependencies
      run: npm i
      working-directory: ./runner

    - name: 🚀 Sync with azure
      run: npm run start
      working-directory: ./runner
      env:
        PAT: ${{secrets.PAT}}
        ORG: ${{secrets.ORG}}
        DAYS_LOOKUP: ${{secrets.DAYS_LOOKUP}}
        COMMITS_FOLDER_PATH: ../tracker

    
